# http://travis-ci.org/#!/gjhiggins/rdflib-sparqlstore
language: python
python:
    - 2.5
    - 2.6
    - 2.7
    - 3.2
install:
    - pip install -r requirements.txt --use-mirrors
    - python setup.py install
script:
    # Must cd somewhere else so python3 doesn't get confused and run
    # the python2 code from the current directory instead of the installed
    # 2to3 version.
    - if [[ $TRAVIS_PYTHON_VERSION == '2.5' ]]; then nosetests; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then nosetests; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then nosetests; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then nosetests --where=./build/src; fi
